[package]
name = "glot-languages"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maud = "0.26.0"
serde = { version = "1.0.208", features = ["derive"] }
